all:
  vars:
    ansible_user: rayan

  children:

    control_plane:
      hosts:
        k8s-1:
          ansible_host: 192.168.1.134
        k8s-2:
          ansible_host: 192.168.1.135
        k8s-3:
          ansible_host: 192.168.1.136

    worker:
      hosts:
        k8s-4:
          ansible_host: 192.168.1.137

    load_balancer:
      hosts:
        haproxy-1:
          ansible_host: 192.168.1.138
          keepalived_state: MASTER
          keepalived_priority: 150

        haproxy-2:
          ansible_host: 192.168.1.140
          keepalived_state: BACKUP
          keepalived_priority: 100
