---
# ---------------------------------------------------------
# 08-01-redis-secret.yml
# Path:
#   infra/ansible/playbooks/08-cache/01-redis-secret.yml
#
# Purpose:
#   Create the Kubernetes Secret used by Redis.
#
# Targets:
#   k8s-1
#
# Security:
#   Redis password is stored in Ansible Vault.
#
# Namespace:
#   cache
#
# Secret:
#   redis
#
# Important:
#   Password is never committed to Git in plaintext.
# ---------------------------------------------------------

- name: "Redis | Create namespace and secret"
  hosts: k8s-1
  become: false
  gather_facts: false

  vars_files:
      - ../../inventory/production/group_vars/redis/08-00-01-redis.yml

  vars:

  vars:

    redis_namespace: "cache"
    redis_secret_name: "redis"

  tasks:

    # -----------------------------------------------------
    # Namespace
    # -----------------------------------------------------

    - name: "Redis | Create namespace"
      ansible.builtin.command:
        cmd: >
          kubectl create namespace {{ redis_namespace }}
      register: redis_namespace_result
      changed_when: redis_namespace_result.rc == 0
      failed_when:
        - redis_namespace_result.rc != 0
        - "'AlreadyExists' not in redis_namespace_result.stderr"

    # -----------------------------------------------------
    # Generate Secret manifest
    # -----------------------------------------------------

    - name: "Redis | Generate Kubernetes Secret manifest"
      ansible.builtin.command:
        cmd: >
          kubectl -n {{ redis_namespace }}
          create secret generic {{ redis_secret_name }}
          --from-literal=redis-password={{ redis_password }}
          --dry-run=client
          -o yaml
      register: redis_secret_manifest
      changed_when: false
      no_log: true

    # -----------------------------------------------------
    # Apply Secret
    # -----------------------------------------------------

    - name: "Redis | Apply Kubernetes Secret"
      ansible.builtin.command:
        cmd: kubectl apply -f -
        stdin: "{{ redis_secret_manifest.stdout }}"
      register: redis_secret_apply
      changed_when: "'created' in redis_secret_apply.stdout or 'configured' in redis_secret_apply.stdout"
      no_log: true
