- name: Deploy to DEV VPS
  uses: appleboy/ssh-action@v1.2.2
  with:
    host: ${{ secrets.DEV_HOST }}
    username: ${{ secrets.DEV_USER }}
    key: ${{ secrets.DEV_SSH_KEY }}
    port: 1256
    script: |
      set -e

      cd /opt/myproject

      export APP_IMAGE=ghcr.io/kamalidariush/mylaravel:${{ github.sha }}

      echo "Deploying image:"
      echo "$APP_IMAGE"

      docker compose pull

      docker compose up -d

      docker compose run --rm app php artisan migrate --force

      docker compose exec -T app php artisan optimize

      docker compose ps